### ISSUE TITLE
Egitim kodu

### ISSUE THREAD

**Issue by muraatozbek** [serdaryildiz/TRCaptionNet#1]
Merhaba, 

egitim kodu eklenicek yazilmis. Ne zaman eklenir acaba?

**Comment by serdaryildiz** [comment]
Merhaba, 

İlginiz için teşekkürler.

TRCaptionNet++ üzerinde çalışıyordum. Planım yeni gelecek repository üzerinden eskisini güncellemekti. Ancak sizin için süreci hızlandırabilirim. 

Önümüzdeki haftaiçi son düzenlemeleri gerçekleştirip kodu paylaşmış olurum.
